services:
  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
